package gsg.corp.driver_data.remote.dto.route

data class RouteDetailDto(
    val RoutePayments: List<RoutePaymentDto>,
    val address: String,
    val address_reference: String,
    val advance: String,
    val code_pay_method: String,
    val code_tracking: String,
    val comment: String,
    val cost: String,
    val date_rescheduled: String,
    val date_route: String,
    val district: String,
    val driver: String,
    val full_name: String,
    val id: Int,
    val id_provider: Int,
    val name_business: String,
    val number_packages: Int,
    val observation: String,
    val other_path_photo_state: String,
    val other_telephone: String,
    val path_photo_state: String,
    val pay_amount: String,
    val product: String,
    val product_detail: String,
    val size: String,
    val st_code: String,
    val st_id: Int,
    val telephone: String
)