package gsg.corp.driver_domain.model

data class RouteDetail(
    val address: String = "",
    val addressReference: String = "",
    val advance: String = "",
    val codePayMethod: String = "",
    val codeTracking: String = "",
    val cost: String = "",
    val dateRoute: String = "",
    val district: String = "",
    val driver: String = "",
    val fullName: String = "",
    val observation:String ="",
    val id: Int = 0,
    val idProvider: Int = 0,
    val nameBusiness: String = "",
    val numberPackages: Int = 0,
    val otherTelephone: String = "",
    val payAmount: String = "",
    val product: String = "",
    val productDetail: String = "",
    val size: String = "",
    val stId: Int = 0,
    val stCode: String = "",
    val telephone: String = "",
    val pathPhotoState: String = "",
    val otherPathPhotoState: String = "",
    val dateRescheduled: String = "",
    val comment: String = "",
    val RoutePayments: List<RoutePayment> = listOf()
)